name: Build USB 2.5G RTL8152 + LuCI for ImmortalWRT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential unzip zstd rsync python3-pip

    - name: Clone SDK
      run: |
        wget https://github.com/immortalwrt/immortalwrt-sdk/releases/download/24.10.1/immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xvf immortalwrt-sdk-*.tar.zst
        mv immortalwrt-sdk-* sdk

    - name: Setup Feeds and Config
      working-directory: ./sdk
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

        cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-base=y
          CONFIG_PACKAGE_luci-mod-network=y
          CONFIG_PACKAGE_luci-proto-ethernet=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          EOF

        make defconfig

    - name: Build Package
      working-directory: ./sdk
      run: |
        make package/kernel/linux/compile V=s CONFIG_PACKAGE_kmod-usb-net-rtl8152=y

    - name: Find Artifacts
      working-directory: ./sdk
      run: |
        find ./bin/packages/ -name '*.ipk'

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-ipks
        path: ./sdk/bin/packages/**/*.ipk
