name: Build USB Network Drivers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses-dev libssl-dev python3 python3-pip python3-setuptools \
          rsync unzip zlib1g-dev libelf-dev ccache rename libtool-bin zstd

    - name: Download ImmortalWRT SDK (.zst format)
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.1/targets/qualcommax/ipq807x/immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    - name: Extract ImmortalWRT SDK
      run: |
        zstd -d immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst -o sdk.tar
        tar -xf sdk.tar
        rm sdk.tar

    - name: Set up SDK environment
      run: |
        cd sdk
        # 初始化 feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile USB 2.5G Network Drivers
      run: |
        cd sdk
        # 这里根据你的需求修改config，例如：
        # echo "CONFIG_USB_NET_R8152=y" >> .config
        # echo "CONFIG_USB_NET_ASIX=y" >> .config
        make defconfig
        make package/kernel/linux/compile V=s

    - name: Upload compiled IPK packages
      uses: actions/upload-artifact@v4
      with:
        name: usb-network-drivers-ipk
        path: |
          sdk/bin/packages/*/base/kmod-usb-net-rtl8152_*.ipk
          sdk/bin/packages/*/base/kmod-usb-net-asix-ax88179_*.ipk
          sdk/bin/packages/*/base/kmod-usb-net_*.ipk
