name: Build USB 2.5G Network Drivers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses-dev libssl-dev python3 python3-pip python3-setuptools \
          rsync unzip zlib1g-dev libelf-dev ccache rename libtool-bin zstd

    - name: Download ImmortalWRT SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.1/targets/qualcommax/ipq807x/immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    - name: Extract SDK
      run: |
        zstd -d immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst -o sdk.tar
        tar -xf sdk.tar
        rm sdk.tar

    - name: Configure build with drivers and LuCI
      run: |
        export SDK_DIR=$(find . -maxdepth 1 -type d -name "immortalwrt-sdk-*")
        cd $SDK_DIR

        cat > .config <<EOF
        CONFIG_PACKAGE_kmod-usb-net=y
        CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-base=y
        CONFIG_PACKAGE_luci-mod-network=y
        CONFIG_PACKAGE_luci-proto-ethernet=y
        CONFIG_PACKAGE_luci-theme-bootstrap=y
        EOF

        make defconfig      
        
    - name: uild USB Drivers and LuCI
      run: |
        export SDK_DIR=$(find . -maxdepth 1 -type d -name "immortalwrt-sdk-*")
        cd $SDK_DIR
        make -j$(nproc)
        
        make package/kernel/linux/compile V=s CONFIG_PACKAGE_kmod-usb-net=y CONFIG_PACKAGE_kmod-usb-net-rtl8152=y

    - name: List All IPK Results
      run: |
        find . -name "kmod-usb-net*.ipk"
        find . -name "luci*.ipk"
        
    - name: Upload RTL8152 Driver Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rtl8152-ipks
        path: |
          **/bin/packages/*/base/kmod-usb-net*.ipk
          **/bin/packages/*/luci/luci*.ipk
