name: Build USB 2.5G RTL8152 + LuCI for ImmortalWRT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses-dev libssl-dev python3 python3-pip python3-setuptools \
          rsync unzip zlib1g-dev libelf-dev ccache rename libtool-bin zstd

    - name: Download ImmortalWRT SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.1/targets/qualcommax/ipq807x/immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    - name: Extract SDK
      run: |
        zstd -d immortalwrt-sdk-24.10.1-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst -o sdk.tar
        tar -xf sdk.tar
        rm sdk.tar

    - name: Configure kernel modules
      run: |
        cd sdk
        echo "CONFIG_PACKAGE_kmod-usb-net=y" >> .config
        echo "CONFIG_PACKAGE_kmod-usb-net-rtl8152=y" >> .config
        make defconfig

    - name: Compile kernel module
      run: |
        cd sdk
        make package/kernel/linux/compile V=s -j$(nproc)

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rtl8152-ipk
        path: |
          sdk/bin/packages/*/base/kmod-usb-net*.ipk
